### ISSUE TITLE
Need Help / Lodash?

### ISSUE THREAD

**Issue by justgage** [reasonml-community/belt#26]
I think Lodash provides in lots of ways a huge wealth of functions that JS programmers are very used it. Modeling this library after that I think would be cool.

One way or another is this something that you are looking for help with?

**Comment by olconstant** [comment]
I think that Ramda has a better API and is more FP style (auto-currying, partial application, and pipe). But Lodash has few useful functions missing in Ramda.

**Comment by justgage** [comment]
I would agree @olconstant. I was thinking we would preserve the currying, piping, etc. I was more or less thinking that all the functions and their names are very useful and clear to JavaScript programmers.

**Comment by AlexGalays** [comment]
imo: lodash has way too many util functions for this and that edge cases (reduce and transform ??!), it also mixes a core of mainly functional functions with some mutable ones, with no easy way to tell one from the other. lodash is also way too dynamic, which is a plague when working with types and trying to achieve good error messages; some functions provide like 5+ arg overloadings.

it's maddening to keep track of all this and make it mandatory to check the documentation all the time. It shouldn't be so. So I don't think lodash is a good inspiration at all if you want a good quality library. I'd rather look at Elm or even scala (and remove a few things)

**Comment by justgage** [comment]
@AlexGalays Yeah I agree, I think that perhaps it's just a place to learn but the more I think about it we should just create "something good" for Reason, since this was just an idea I'll close this.

**Comment by langri-sha** [comment]
There's a Ramda-inspired library https://github.com/jonlaing/rationale.
